#data: data/cnndm/CNNDM
save_model: models/baseline_europarl
save_checkpoint_steps: 100000
keep_checkpoint: 10
seed: 3435
train_steps: 200000
valid_steps: 10000
report_every: 100
model_type: text

global_attention: general

encoder_type: brnn
word_vec_size: 1024
enc_rnn_size: 1024
enc_layers: 2
rnn_type: LSTM

decoder_type: rnn
word_vec_size: 1024
dec_rnn_size: 1024
dec_layers: 2
rnn_type: LSTM

optim: adam #adagrad
learning_rate: 0.001 #0.1
adagrad_accumulator_init: 0.1
max_grad_norm: 2
start_decay_steps: 100000
learning_rate_decay: 0.1

batch_size: 128
dropout: 0.1

bridge: 'true'

world_size: 1
gpu_ranks:
- 0
